### ISSUE TITLE
Requires authentication on every startup

### ISSUE THREAD

**Issue by GCTuba** [GooglyBlox/playnite-stove-plugin#6]
I noticed a couple days ago that I have to log in to Stove every time Playnite starts. Authentication is successful but it shouldn't be necessary every time.

**Comment by GooglyBlox** [comment]
I'm experiencing that as well, will look into it!

**Comment by GooglyBlox** [comment]
Should be fixed in [v2.1](https://github.com/GooglyBlox/playnite-stove-plugin/releases/tag/v2.1), but it'll take a little bit of testing to make sure. Gonna leave this open for a day or two more and if neither you nor I experience it again, I'll close this issue!

**Comment by GCTuba** [comment]
> Should be fixed in [v2.1](https://github.com/GooglyBlox/playnite-stove-plugin/releases/tag/v2.1), but it'll take a little bit of testing to make sure. Gonna leave this open for a day or two more and if neither you nor I experience it again, I'll close this issue!

Looks like the 2.1 update didn't solve the issue, I'm still having to authenticate at every startup.

**Comment by GooglyBlox** [comment]
Looks like it, back to the drawing board

**Comment by GCTuba** [comment]
> Looks like it, back to the drawing board

Any progress?

**Comment by GCTuba** [comment]
@GooglyBlox Don't wanna be a bother, I was just curious if this was a plugin you're still planning on working on/maintaining. It's been a while since there's been any update.

**Comment by GooglyBlox** [comment]
It's no bother at all, I'm sorry for the lack of response! Things have been so busy lately with work and I haven't really had a chance to rewrite the auth flow properly. I'm definitely still interested in maintaining this repository, and I'll try to get it fixed ASAP.

**Comment by GooglyBlox** [comment]
Hi, so sorry for the wait! 

I've finally identified what I believe is the issue and resolved it. I've been running the fix over the last few days, and haven't had any issues. I'm going to close this issue as resolved in [v2.2](https://github.com/GooglyBlox/playnite-stove-plugin/releases/tag/v2.2). If it occurs again, please reopen this issue!

**Comment by GCTuba** [comment]
Thank you for the update! So far so good.
